wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.0
    start_time: 1673430914.019283
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.11.0
      5: 0.13.7
      8:
      - 5
